# Generated by Django 3.1.2 on 2021-03-09 12:33

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocationmodel',
            name='address',
            field=mapbox_location_field.models.AddressAutoHiddenField(default='Rawalpindi', map_id='map'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlocationmodel',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [0, 0], 'marker_color': 'blue'}),
        ),
    ]
