# Generated by Django 3.1.2 on 2021-03-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20210309_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocationmodel',
            name='address',
        ),
    ]
