# Generated by Django 3.1.2 on 2021-03-09 15:56

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_remove_userlocationmodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocationmodel',
            name='address',
            field=mapbox_location_field.models.AddressAutoHiddenField(default='Rawalpindiiii', map_id='map'),
            preserve_default=False,
        ),
    ]
